#!/bin/sh
set -e

case "$1" in
  remove)
    rmdir --ignore-fail-on-non-empty /var/lib/vcpkg-deb 2>/dev/null || true
    ;;
  purge)
    rm -rf /var/lib/vcpkg-deb || {
	  echo "Warning: failed to remove /var/lib/vcpkg-deb" >&2
	  true
	}
    ;;
  *)
    # No action needed for other cases
    ;;
esac

exit 0
