name: Release on Tag

on:
  push:
    tags:
      - '*[0-9]*.[0-9]*.[0-9]*'
  workflow_run:
    workflows: ["build-deb"]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Download Debian package artifact
        uses: actions/download-artifact@v4
        with:
          name: vcpkg-deb_${{ github.ref_name }}_all.deb
          path: ./vcpkg-deb_${{ github.ref_name }}_all.deb

      - name: Publish assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./vcpkg-deb_${{ github.ref_name }}_all.deb
          asset_name: vcpkg-deb_${{ github.ref_name }}_all.deb
          asset_content_type: application/vnd.debian.binary-package
